apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-learn-deployment
  labels:
    app: kubernetes-learn
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-learn
  template:
    metadata:
      labels:
        app: kubernetes-learn
    spec:
      containers:
      - name: kubernetes-learn-container
        image: chandreyees20/kubernetes-assignment:01
        ports:
        - containerPort: 9090
