apiVersion: v1
kind: Service
metadata:
  name: kubernetes-learn-service
spec:
  selector:
    app: kubernetes-learn
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
  type: LoadBalancer
